"""Graphiti 0.30.2 retrievable-EntityEdge capability.

The selected public result class is ``EntityEdge`` from ``Graphiti.search()``.
Inventory uses the public ``graphiti.edges.entity.get_by_group_ids`` namespace,
which the pinned Neo4j implementation defines over the same group-scoped
``RELATES_TO`` EntityEdge class.  Episode traversal is deliberately not an
inventory source: one edge may belong to several episodes, and an EntityEdge
need not be recoverable from the adapter's initialized episode backreferences.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
import json
from typing import Any
from uuid import UUID

from ufuzz.backends.base import StateHandle
from ufuzz.backends.graphiti import GRAPHITI_TAG_COMMIT, GRAPHITI_VERSION
from ufuzz.coverage import PhysicalEntryRef
from ufuzz.retrieval_capability import (
    CapabilityOperation,
    CapabilityResult,
    RankedPhysicalRetrieval,
    RetrievableEntryInventory,
    RetrievableEntryProjection,
    RetrievableInventoryEntry,
    RetrievalCapabilityBlocker,
)


GRAPHITI_PUBLIC_RETRIEVAL_API = "Graphiti.search"
GRAPHITI_INVENTORY_API = "Graphiti.edges.entity.get_by_group_ids"
GRAPHITI_RETRIEVAL_OBJECT_CLASS = "EntityEdge"
UFUZZ_ATTRIBUTE_PREFIX = "ufuzz_"
ENTITY_NODE_STORAGE_FIELDS = frozenset(
    {
        "uuid",
        "name",
        "group_id",
        "name_embedding",
        "summary",
        "created_at",
        "labels",
    }
)
ENTITY_EDGE_STORAGE_FIELDS = frozenset(
    {
        "uuid",
        "source_node_uuid",
        "target_node_uuid",
        "fact",
        "fact_embedding",
        "name",
        "group_id",
        "episodes",
        "created_at",
        "expired_at",
        "valid_at",
        "invalid_at",
        "reference_time",
    }
)


@dataclass(frozen=True, slots=True)
class GraphitiScope:
    """The existing adapter's one-StateHandle group/database boundary."""

    state_id: str
    group_id: str
    database: str | None
    backend_object_identity: int


class _GraphitiCapabilityFailure(ValueError):
    def __init__(self, operation: CapabilityOperation, reason: str) -> None:
        self.operation = operation
        super().__init__(reason)


def _field(value: Any, name: str) -> Any:
    return value.get(name) if isinstance(value, Mapping) else getattr(value, name, None)


def _canonical_uuid(value: Any, *, where: str) -> str:
    """Accept only the canonical UUID strings generated by Graphiti 0.30.2."""

    if not isinstance(value, str) or not value:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PHYSICAL_IDENTITY,
            f"{where} has a missing, empty, or non-string UUID",
        )
    try:
        parsed = UUID(value)
    except (ValueError, AttributeError) as error:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PHYSICAL_IDENTITY,
            f"{where} has a malformed UUID",
        ) from error
    if str(parsed) != value:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PHYSICAL_IDENTITY,
            f"{where} UUID is not in Graphiti's canonical representation",
        )
    return value


def _exact_string(value: Any, *, field: str) -> str:
    if not isinstance(value, str):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            f"Graphiti public {field} is not a string",
        )
    return value


def _string_sequence(value: Any, *, field: str) -> tuple[str, ...]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            f"Graphiti public {field} is not a sequence",
        )
    if any(not isinstance(item, str) for item in value):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            f"Graphiti public {field} contains a non-string value",
        )
    return tuple(value)


def _stable_attributes(
    value: Any,
    *,
    field: str,
    reserved_fields: frozenset[str],
) -> dict[str, Any]:
    """Keep semantic public attributes and remove exact storage/harness keys.

    Graphiti's pinned record parsers remove these top-level model/storage fields
    from ``attributes`` after reading ``properties(...)``. The adapter supplies
    no custom entity/edge schemas, so initialized attributes are normally empty;
    any remaining public custom fields are semantic model attributes and remain
    exact. Nested values are not rewritten because the pinned source does not
    inject storage metadata beneath custom fields.
    """

    if not isinstance(value, Mapping) or any(not isinstance(key, str) for key in value):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            f"Graphiti public {field} is not a string-keyed mapping",
        )
    return {
        key: item
        for key, item in value.items()
        if key not in reserved_fields and not key.startswith(UFUZZ_ATTRIBUTE_PREFIX)
    }


def _temporal_value(value: Any, *, field: str) -> str | None:
    """Represent public temporal state exactly, without semantic normalization."""

    if value is None:
        return None
    if not isinstance(value, datetime):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            f"Graphiti public {field} is not a datetime or None",
        )
    return value.isoformat()


def _node_projection(node: Any, *, role: str) -> dict[str, Any]:
    """Replace replay-local endpoint UUIDs with exact public node state.

    Neo4j labels are a set-like schema property and Graphiti itself constructs
    them through set operations, so labels receive representation-only exact
    string sorting. Names, summaries, and attributes remain exact.
    """

    labels = _string_sequence(_field(node, "labels"), field=f"{role} endpoint labels")
    return {
        "name": _exact_string(_field(node, "name"), field=f"{role} endpoint name"),
        "summary": _exact_string(
            _field(node, "summary"), field=f"{role} endpoint summary"
        ),
        "labels": tuple(sorted(labels)),
        "attributes": _stable_attributes(
            _field(node, "attributes"),
            field=f"{role} endpoint attributes",
            reserved_fields=ENTITY_NODE_STORAGE_FIELDS,
        ),
    }


def graphiti_observable_projection(
    edge: Any,
    *,
    source_node: Any,
    target_node: Any,
    episode_provenance: Sequence[Sequence[str]],
) -> RetrievableEntryProjection:
    """Project exact replay-stable public EntityEdge state.

    Included fields are exact edge name/fact, stable endpoint node projections,
    ordered stable episode provenance, temporal validity/reference fields, and
    public attributes. Edge/node UUIDs, group ID, created-at values, embeddings,
    and search rank/score are replay-local, volatile, or query-specific and are
    excluded. ``expired_at`` itself is also excluded because this adapter path
    assigns it with ``utc_now()`` during invalidation. Its stable state meaning
    is retained as ``is_expired`` so wall-clock-only timestamp differences do
    not make faithful replays inequivalent.

    The outer episode order remains exact because ``remove_episode`` treats
    ``edge.episodes[0]`` as the creating episode. Stable provenance values
    within one adapter episode are set-like and receive exact-string ordering;
    neither outer multiplicity nor position is erased.
    """

    edge_source = _canonical_uuid(
        _field(edge, "source_node_uuid"), where="EntityEdge source endpoint"
    )
    edge_target = _canonical_uuid(
        _field(edge, "target_node_uuid"), where="EntityEdge target endpoint"
    )
    if _canonical_uuid(_field(source_node, "uuid"), where="source EntityNode") != edge_source:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti source endpoint projection does not match EntityEdge",
        )
    if _canonical_uuid(_field(target_node, "uuid"), where="target EntityNode") != edge_target:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti target endpoint projection does not match EntityEdge",
        )

    raw_episodes = _string_sequence(_field(edge, "episodes"), field="EntityEdge episodes")
    for episode_id in raw_episodes:
        _canonical_uuid(episode_id, where="EntityEdge episode")
    if len(raw_episodes) != len(episode_provenance):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti stable episode provenance does not match EntityEdge episodes",
        )

    stable_episodes: list[tuple[str, ...]] = []
    for values in episode_provenance:
        provenance = _string_sequence(values, field="episode provenance")
        if not provenance or any(not item for item in provenance):
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.PROJECTION,
                "Graphiti episode has no stable U-Fuzz provenance",
            )
        stable_episodes.append(tuple(sorted(provenance)))

    expired_at = _field(edge, "expired_at")
    _temporal_value(expired_at, field="expired_at")

    return RetrievableEntryProjection(
        backend="graphiti",
        retrieval_object_class=GRAPHITI_RETRIEVAL_OBJECT_CLASS,
        observable={
            "name": _exact_string(_field(edge, "name"), field="EntityEdge name"),
            "fact": _exact_string(_field(edge, "fact"), field="EntityEdge fact"),
            "source": _node_projection(source_node, role="source"),
            "target": _node_projection(target_node, role="target"),
            "episode_provenance": tuple(stable_episodes),
            "valid_at": _temporal_value(_field(edge, "valid_at"), field="valid_at"),
            "invalid_at": _temporal_value(
                _field(edge, "invalid_at"), field="invalid_at"
            ),
            "is_expired": expired_at is not None,
            "reference_time": _temporal_value(
                _field(edge, "reference_time"), field="reference_time"
            ),
            "attributes": _stable_attributes(
                _field(edge, "attributes"),
                field="EntityEdge attributes",
                reserved_fields=ENTITY_EDGE_STORAGE_FIELDS,
            ),
        },
    )


def graphiti_scope_from_state(state: StateHandle) -> GraphitiScope:
    """Validate the group namespace already owned by GraphitiAdapter."""

    if state.backend != "graphiti":
        raise ValueError("Graphiti capability requires a Graphiti state")
    group_id = state.metadata.get("group_id")
    if group_id != state.state_id:
        raise ValueError("Graphiti group does not match the adapter state namespace")
    backend = state.backend_state
    entity_edges = getattr(getattr(backend, "edges", None), "entity", None)
    entity_nodes = getattr(getattr(backend, "nodes", None), "entity", None)
    episode_nodes = getattr(getattr(backend, "nodes", None), "episode", None)
    required = (
        getattr(entity_edges, "get_by_group_ids", None),
        getattr(entity_nodes, "get_by_uuids", None),
        getattr(episode_nodes, "get_by_uuids", None),
        getattr(backend, "search", None),
    )
    if not all(callable(item) for item in required):
        raise ValueError("Graphiti state lacks required public edge/node namespace APIs")
    database = state.metadata.get("database")
    if database is not None and not isinstance(database, str):
        raise ValueError("Graphiti database scope is not a string or None")
    return GraphitiScope(state.state_id, group_id, database, id(backend))


def _episode_provenance(episode: Any) -> tuple[str, ...]:
    description = _field(episode, "source_description")
    if not isinstance(description, str):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti episode source_description is not a string",
        )
    try:
        payload = json.loads(description)
    except json.JSONDecodeError as error:
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti episode source_description is not U-Fuzz provenance JSON",
        ) from error
    if not isinstance(payload, Mapping):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti episode source_description is not a mapping",
        )
    if "ufuzz_provenance_id" in payload:
        values: Any = (payload["ufuzz_provenance_id"],)
    else:
        values = payload.get("ufuzz_provenance_ids")
    provenance = _string_sequence(values, field="episode provenance")
    if not provenance or any(not value for value in provenance):
        raise _GraphitiCapabilityFailure(
            CapabilityOperation.PROJECTION,
            "Graphiti episode has no stable U-Fuzz provenance",
        )
    return tuple(dict.fromkeys(provenance))


class GraphitiRetrievableEntryCapability:
    """Concrete public-EntityEdge capability for one isolated Graphiti state."""

    backend = "graphiti"
    selected_public_retrieval_api = GRAPHITI_PUBLIC_RETRIEVAL_API
    retrieval_object_class = GRAPHITI_RETRIEVAL_OBJECT_CLASS

    def __init__(self, state: StateHandle) -> None:
        self.state = state
        self.scope = graphiti_scope_from_state(state)

    def _blocker(
        self,
        root_checkpoint_id: str,
        operation: CapabilityOperation,
        reason: str,
    ) -> CapabilityResult[Any]:
        return CapabilityResult.failure(
            RetrievalCapabilityBlocker("graphiti", root_checkpoint_id, operation, reason)
        )

    def _validate_request_scope(self, root_checkpoint_id: str, state_id: str) -> None:
        if root_checkpoint_id != self.state.checkpoint_id:
            raise ValueError("Graphiti capability request uses another root checkpoint")
        if state_id != self.state.state_id:
            raise ValueError("Graphiti capability request uses another backend state")
        if graphiti_scope_from_state(self.state) != self.scope:
            raise ValueError("Graphiti StateHandle no longer owns its original graph scope")

    async def _snapshot(
        self,
    ) -> dict[str, tuple[RetrievableEntryProjection, tuple[str, ...]]]:
        """Enumerate the complete group EntityEdge class through public APIs.

        In graphiti-core 0.30.2 the public namespace forwards ``limit=None``
        and ``uuid_cursor=None`` to Neo4j operations. Those values omit both the
        ``LIMIT`` and UUID-cursor clauses, so the query returns every group-scoped
        ``(Entity)-[e:RELATES_TO]->(Entity)`` object—the exact class searched by
        ``Graphiti.search``. A fact embedding is not required: BM25 is an
        independent candidate branch and RRF retains UUIDs present in only that
        branch.
        """

        backend = self.state.backend_state
        values = await backend.edges.entity.get_by_group_ids(
            [self.scope.group_id], limit=None, uuid_cursor=None
        )
        if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.INVENTORY,
                f"{GRAPHITI_INVENTORY_API} did not return a sequence",
            )

        edges_by_id: dict[str, list[Any]] = {}
        for edge in values:
            edge_id = _canonical_uuid(_field(edge, "uuid"), where="EntityEdge")
            if _field(edge, "group_id") != self.scope.group_id:
                raise _GraphitiCapabilityFailure(
                    CapabilityOperation.INVENTORY,
                    "Graphiti group inventory returned an edge from another group",
                )
            edges_by_id.setdefault(edge_id, []).append(edge)

        endpoint_ids = {
            _canonical_uuid(_field(edge, field), where=f"EntityEdge {field}")
            for group in edges_by_id.values()
            for edge in group
            for field in ("source_node_uuid", "target_node_uuid")
        }
        episode_ids = {
            _canonical_uuid(value, where="EntityEdge episode")
            for group in edges_by_id.values()
            for edge in group
            for value in _string_sequence(_field(edge, "episodes"), field="EntityEdge episodes")
        }

        nodes = (
            await backend.nodes.entity.get_by_uuids(sorted(endpoint_ids)) if endpoint_ids else []
        )
        episodes = (
            await backend.nodes.episode.get_by_uuids(sorted(episode_ids)) if episode_ids else []
        )
        nodes_by_id = self._objects_by_id(nodes, endpoint_ids, kind="EntityNode")
        episodes_by_id = self._objects_by_id(episodes, episode_ids, kind="EpisodicNode")

        snapshot: dict[str, tuple[RetrievableEntryProjection, tuple[str, ...]]] = {}
        for edge_id, discoveries in edges_by_id.items():
            candidate_values: list[tuple[RetrievableEntryProjection, tuple[str, ...]]] = []
            for edge in discoveries:
                source_id = _canonical_uuid(
                    _field(edge, "source_node_uuid"), where="EntityEdge source endpoint"
                )
                target_id = _canonical_uuid(
                    _field(edge, "target_node_uuid"), where="EntityEdge target endpoint"
                )
                ordered_episode_ids = _string_sequence(
                    _field(edge, "episodes"), field="EntityEdge episodes"
                )
                ordered_provenance = tuple(
                    _episode_provenance(episodes_by_id[episode_id])
                    for episode_id in ordered_episode_ids
                )
                projection = graphiti_observable_projection(
                    edge,
                    source_node=nodes_by_id[source_id],
                    target_node=nodes_by_id[target_id],
                    episode_provenance=ordered_provenance,
                )
                provenance = tuple(
                    dict.fromkeys(
                        item for values_for_episode in ordered_provenance for item in values_for_episode
                    )
                )
                candidate_values.append((projection, provenance))
            if any(value != candidate_values[0] for value in candidate_values[1:]):
                raise _GraphitiCapabilityFailure(
                    CapabilityOperation.INVENTORY,
                    "duplicate discovery of one Graphiti edge UUID disagrees in public state",
                )
            snapshot[edge_id] = candidate_values[0]
        return snapshot

    def _objects_by_id(
        self,
        values: Any,
        expected: set[str],
        *,
        kind: str,
    ) -> dict[str, Any]:
        if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.INVENTORY,
                f"Graphiti public {kind} lookup did not return a sequence",
            )
        result: dict[str, Any] = {}
        for value in values:
            object_id = _canonical_uuid(_field(value, "uuid"), where=kind)
            if object_id in result:
                raise _GraphitiCapabilityFailure(
                    CapabilityOperation.INVENTORY,
                    f"Graphiti public {kind} lookup returned a duplicate UUID",
                )
            if _field(value, "group_id") != self.scope.group_id:
                raise _GraphitiCapabilityFailure(
                    CapabilityOperation.INVENTORY,
                    f"Graphiti public {kind} lookup returned another group",
                )
            result[object_id] = value
        if set(result) != expected:
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.INVENTORY,
                f"Graphiti public {kind} lookup did not exactly resolve inventory references",
            )
        return result

    async def _stable_snapshot(
        self,
    ) -> dict[str, tuple[RetrievableEntryProjection, tuple[str, ...]]]:
        """Repeat exact public enumeration; no mutation may run concurrently."""

        first = await self._snapshot()
        second = await self._snapshot()
        if first.keys() != second.keys():
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.INVENTORY,
                "stable Graphiti initialization snapshot could not be established: UUID set changed",
            )
        if first != second:
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.INVENTORY,
                "stable Graphiti initialization snapshot could not be established: "
                "projection or provenance changed",
            )
        return first

    async def inventory(
        self,
        *,
        campaign_id: str,
        root_checkpoint_id: str,
        state_id: str,
    ) -> CapabilityResult[RetrievableEntryInventory]:
        try:
            self._validate_request_scope(root_checkpoint_id, state_id)
            snapshot = await self._stable_snapshot()
            entries = tuple(
                RetrievableInventoryEntry(
                    PhysicalEntryRef(campaign_id, root_checkpoint_id, state_id, edge_id),
                    projection,
                    provenance,
                )
                for edge_id, (projection, provenance) in snapshot.items()
            )
            return CapabilityResult.success(
                RetrievableEntryInventory(
                    backend="graphiti",
                    selected_public_retrieval_api=GRAPHITI_PUBLIC_RETRIEVAL_API,
                    retrieval_object_class=GRAPHITI_RETRIEVAL_OBJECT_CLASS,
                    retrieval_returnability_basis=(
                        f"graphiti-core {GRAPHITI_VERSION} ({GRAPHITI_TAG_COMMIT}): "
                        "Graphiti.search and the public entity-edge group namespace use "
                        "the same group-scoped RELATES_TO EntityEdge class; no default "
                        "validity filter applies, limit/cursor clauses are absent, BM25 "
                        "returnability does not require an embedding, and the exact "
                        "snapshot was repeated"
                    ),
                    campaign_id=campaign_id,
                    root_checkpoint_id=root_checkpoint_id,
                    state_id=state_id,
                    entries=entries,
                )
            )
        except _GraphitiCapabilityFailure as error:
            return self._blocker(root_checkpoint_id, error.operation, str(error))
        except Exception as error:
            return self._blocker(
                root_checkpoint_id,
                CapabilityOperation.INVENTORY,
                f"scoped Graphiti inventory could not be established: {error}",
            )

    async def retrieve(
        self,
        *,
        campaign_id: str,
        root_checkpoint_id: str,
        state_id: str,
        query: str,
        top_k: int,
    ) -> CapabilityResult[RankedPhysicalRetrieval]:
        try:
            self._validate_request_scope(root_checkpoint_id, state_id)
            values = await self.state.backend_state.search(
                query,
                group_ids=[self.scope.group_id],
                num_results=top_k,
            )
            return CapabilityResult.success(
                self.ranked_retrieval_from_search_result(
                    values,
                    campaign_id=campaign_id,
                    root_checkpoint_id=root_checkpoint_id,
                    state_id=state_id,
                )
            )
        except _GraphitiCapabilityFailure as error:
            return self._blocker(root_checkpoint_id, error.operation, str(error))
        except Exception as error:
            return self._blocker(
                root_checkpoint_id,
                CapabilityOperation.RANKED_RETRIEVAL,
                f"scoped Graphiti search could not be established: {error}",
            )

    def ranked_retrieval_from_search_result(
        self,
        values: Any,
        *,
        campaign_id: str,
        root_checkpoint_id: str,
        state_id: str,
    ) -> RankedPhysicalRetrieval:
        """Preserve public Graphiti.search rank and exact EntityEdge UUIDs."""

        self._validate_request_scope(root_checkpoint_id, state_id)
        if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
            raise _GraphitiCapabilityFailure(
                CapabilityOperation.RANKED_RETRIEVAL,
                "Graphiti.search did not return an EntityEdge sequence",
            )
        physical: list[PhysicalEntryRef] = []
        for edge in values:
            edge_id = _canonical_uuid(_field(edge, "uuid"), where="Graphiti.search EntityEdge")
            if _field(edge, "group_id") != self.scope.group_id:
                raise _GraphitiCapabilityFailure(
                    CapabilityOperation.RANKED_RETRIEVAL,
                    "Graphiti.search returned an EntityEdge from another group",
                )
            _exact_string(_field(edge, "name"), field="EntityEdge name")
            _exact_string(_field(edge, "fact"), field="EntityEdge fact")
            physical.append(
                PhysicalEntryRef(campaign_id, root_checkpoint_id, state_id, edge_id)
            )
        return RankedPhysicalRetrieval(
            backend="graphiti",
            selected_public_retrieval_api=GRAPHITI_PUBLIC_RETRIEVAL_API,
            retrieval_object_class=GRAPHITI_RETRIEVAL_OBJECT_CLASS,
            campaign_id=campaign_id,
            root_checkpoint_id=root_checkpoint_id,
            state_id=state_id,
            ranked_physical_entries=tuple(physical),
        )
